name:                haskvc
version:             0.1.0.0
github:              "fshcat/haskvc"
license:             BSD3
author:              "Fishcat & Ambika Nair"
maintainer:          "rosalogia@protonmail.ch"
copyright:           "2020 Fishcat & Ambika Nair"

extra-source-files: []

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fshcat/haskvc#readme>

dependencies:
- base >= 4.7 && < 5
- process == 1.6.10.0
- parsec == 3.1.14.0
- directory == 1.3.6.0
- containers == 0.6.2.1
  
library:
  source-dirs: src

executables:
  haskvc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskvc

tests:
  haskvc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskvc
